//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactoryPatterns.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Factories : global::System.Configuration.ApplicationSettingsBase {
        
        private static Factories defaultInstance = ((Factories)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Factories())));
        
        public static Factories Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FactoryPatterns.Factories.MiniCooperFactory")]
        public string AutoFactory {
            get {
                return ((string)(this["AutoFactory"]));
            }
            set {
                this["AutoFactory"] = value;
            }
        }
    }
}
